$kind: http-example
request:
  url: "{{baseUrl}}/server/admin/containers/:containerId/tasks/:taskInstanceId/er\
    rors?includeAck=false&page=0&pageSize=10&sort=string&sortOrder=true"
  method: GET
  queryParams:
    - key: includeAck
      value: "false"
      description: optional flag that indicates if acknowledged errors should also be
        collected, defaults to false
    - key: page
      value: "0"
      description: optional pagination - at which page to start, defaults to 0
        (meaning first)
    - key: pageSize
      value: "10"
      description: optional pagination - size of the result, defaults to 10
    - key: sort
      value: string
      description: optional sort column, no default
    - key: sortOrder
      value: "true"
      description: optional sort direction (asc, desc) - defaults to asc
  pathVariables:
    - key: containerId
      value: evaluation_1.0.0-SNAPSHOT
      description: container id that task instance belongs to
    - key: taskInstanceId
      value: "123"
      description: identifier of the task instance that errors should be collected for
response:
  statusCode: 404
  statusText: Not Found
  body:
    type: text
    content: ""
order: 2000
