$kind: http-request
url: "{{baseUrl}}/server/containers/:containerId/tasks/:taskInstanceId/states/s\
  kipped?user=string"
method: PUT
queryParams:
  - key: user
    value: string
    description: optional user id to be used instead of authenticated user - only
      when bypass authenticated user is enabled
pathVariables:
  - key: containerId
    value: evaluation_1.0.0-SNAPSHOT
    description: container id that task instance belongs to
  - key: taskInstanceId
    value: "123"
    description: identifier of the task instance that should be skipped
examples: ./.resources/Skips a specified task instance within the sequence of
  tasks in the process instance.resources/examples
order: 1000
