$kind: http-example
request:
  url: "{{baseUrl}}/server/admin/containers/:containerId/tasks/:taskInstanceId/co\
    ntents/input?name=string"
  method: DELETE
  queryParams:
    - key: name
      value: string
      description: one or more names of task inputs to be removed
  pathVariables:
    - key: containerId
      value: evaluation_1.0.0-SNAPSHOT
      description: container id that task instance belongs to
    - key: taskInstanceId
      value: "123"
      description: identifier of task instance to be updated
response:
  statusCode: 404
  statusText: Not Found
  body:
    type: text
    content: ""
order: 1000
