$kind: http-request
url: "{{baseUrl}}/server/admin/containers/:containerId/tasks/:taskInstanceId/no\
  tifications/:notificationId"
method: DELETE
pathVariables:
  - key: containerId
    value: evaluation_1.0.0-SNAPSHOT
    description: container id that task instance belongs to
  - key: taskInstanceId
    value: "123"
    description: identifier of task instance to be updated
  - key: notificationId
    value: "567"
    description: identifier of notification to be canceled
examples: ./.resources/Deletes a specified email notification from a specified
  task instance..resources/examples
order: 1000
