$kind: http-example
request:
  url: "{{baseUrl}}/server/admin/containers/:containerId/tasks/errors/:errorId"
  method: PUT
  pathVariables:
    - key: containerId
      value: evaluation_1.0.0-SNAPSHOT
      description: container id that error belongs to
    - key: errorId
      value: xxx-yyy-zzz
      description: identifier of the execution error to be acknowledged
response:
  statusCode: 404
  statusText: Not Found
  body:
    type: text
    content: ""
order: 1000
