$kind: http-example
request:
  url: "{{baseUrl}}/server/containers/:containerId/cases/instances/:caseId/roles/\
    :caseRoleName?user=string&group=string"
  method: DELETE
  queryParams:
    - key: user
      value: string
      description: user to be removed from case role for given case instance
    - key: group
      value: string
      description: group to be removed from case role for given case instance
  pathVariables:
    - key: containerId
      value: evaluation_1.0.0-SNAPSHOT
      description: container id that case instance belongs to
    - key: caseId
      value: CASE-00000000001
      description: identifier of the case instance
    - key: caseRoleName
      value: owner
      description: name of the case role the assignment should be removed
response:
  statusCode: 404
  statusText: Not Found
  body:
    type: text
    content: ""
order: 1000
