$kind: http-request
url: "{{baseUrl}}/server/containers/:containerId/tasks/:taskInstanceId/comments\
  /:commentId"
method: GET
headers:
  Accept: application/json
pathVariables:
  - key: containerId
    value: evaluation_1.0.0-SNAPSHOT
    description: container id that task instance belongs to
  - key: taskInstanceId
    value: "123"
    description: identifier of the task instance that comment belongs to
  - key: commentId
    value: "567"
    description: identifier of the comment to be loaded
examples: ./.resources/Returns a specified comment from a specified task
  instance..resources/examples
order: 1000
