$kind: http-request
url: "{{baseUrl}}/server/containers/:containerId/tasks/:taskInstanceId/comments"
method: GET
headers:
  Accept: application/json
pathVariables:
  - key: containerId
    value: evaluation_1.0.0-SNAPSHOT
    description: container id that task instance belongs to
  - key: taskInstanceId
    value: "123"
    description: identifier of the task instance that comments should be loaded for
examples: ./.resources/Returns all comments in a specified task
  instance..resources/examples
order: 2000
