$kind: http-request
url: "{{baseUrl}}/server/queries/tasks/instances/workitem/:workItemId"
method: GET
headers:
  Accept: application/json
pathVariables:
  - key: workItemId
    value: "3284"
    description: work item id to load task associated with
examples: ./.resources/Returns task instances with a specified work
  item..resources/examples
order: 1000
