$kind: http-request
url: "{{baseUrl}}/server/admin/containers/:containerId/tasks/:taskInstanceId/re\
  assignments?activeOnly=true"
method: GET
headers:
  Accept: application/json
queryParams:
  - key: activeOnly
    value: "true"
    description: optional flag that indicates if active only reassignmnets should be
      collected, defaults to true
pathVariables:
  - key: containerId
    value: evaluation_1.0.0-SNAPSHOT
    description: container id that task instance belongs to
  - key: taskInstanceId
    value: "123"
    description: identifier of task instance to be updated
examples: ./.resources/Returns task reassignments for a specified task
  instance..resources/examples
order: 2000
