$kind: http-example
request:
  url: "{{baseUrl}}/server/containers/:containerId/cases/instances/:caseId/stages\
    /:caseStageId/tasks/:nodeName"
  method: PUT
  headers:
    Content-Type: application/json
  pathVariables:
    - key: containerId
      value: evaluation_1.0.0-SNAPSHOT
      description: container id that case instance belongs to
    - key: caseId
      value: CASE-00000000001
      description: identifier of the case instance
    - key: caseStageId
      value: stageOne
      description: identifier of the stage within case instance where adhoc fragment
        should be triggered
    - key: nodeName
      value: string
      description: name of the adhoc fragment to be triggered
  body:
    type: json
    content: string
response:
  statusCode: 404
  statusText: Not Found
  body:
    type: text
    content: ""
order: 1000
