$kind: http-example
request:
  url: "{{baseUrl}}/server/admin/containers/:containerId/tasks/:taskInstanceId/no\
    tifications?activeOnly=true"
  method: GET
  headers:
    Accept: application/json
  queryParams:
    - key: activeOnly
      value: "true"
      description: optional flag that indicates if active only notifications should be
        collected, defaults to true
  pathVariables:
    - key: containerId
      value: evaluation_1.0.0-SNAPSHOT
      description: container id that task instance belongs to
    - key: taskInstanceId
      value: "123"
      description: identifier of task instance to be updated
response:
  statusCode: 200
  statusText: OK
  headers:
    Content-Type: application/json
  body:
    type: json
    content: >-
      {
        "task-notification": [
          {
            "id": 11070,
            "name": null,
            "notify-at": 1540396524172,
            "users": [
              "Sheldon"
            ],
            "groups": [
              "IT"
            ],
            "active": true,
            "subject": "You hava a task not started",
            "content": "You have been assigned to a task (task-id ${taskId}).\n  Important technical information that can be of use when working on it:\n    - process instance id - ${processInstanceId}\n  - work item id - ${workItemId}\n  - work item id - ${workItemId}\n   Regards from dev team"
          }
        ]
      }
order: 1000
