$kind: http-example
request:
  url: "{{baseUrl}}/server/admin/containers/:containerId/tasks/:taskInstanceId/no\
    tifications?activeOnly=true"
  method: GET
  queryParams:
    - key: activeOnly
      value: "true"
      description: optional flag that indicates if active only notifications should be
        collected, defaults to true
  pathVariables:
    - key: containerId
      value: evaluation_1.0.0-SNAPSHOT
      description: container id that task instance belongs to
    - key: taskInstanceId
      value: "123"
      description: identifier of task instance to be updated
response:
  statusCode: 500
  statusText: Internal Server Error
  body:
    type: text
    content: ""
order: 3000
