$kind: http-request
url: "{{baseUrl}}/server/admin/containers/:containerId/tasks/:taskInstanceId/ad\
  mins/groups/:entityId?user=string"
method: DELETE
queryParams:
  - key: user
    value: string
    description: optional user id to be used instead of authenticated user - only
      when bypass authenticated user is enabled
pathVariables:
  - key: containerId
    value: string
    description: container id that task instance belongs to
  - key: taskInstanceId
    value: "3284"
    description: identifier of task instance to be updated
  - key: entityId
    value: HR
    description: list of groups to be removed from business admin list
examples: ./.resources/Deletes specified groups previously added as business
  administrators for a specified task instance..resources/examples
order: 1000
