$kind: http-example
request:
  url: "{{baseUrl}}/server/containers/:containerId/processes/definitions/:process\
    Id/tasks/users"
  method: GET
  headers:
    Accept: application/json
  pathVariables:
    - key: containerId
      value: evaluation_1.0.0-SNAPSHOT
      description: container id where the process definition resides
    - key: processId
      value: evaluation
      description: process id that the user task definitions should be retrieved from
response:
  statusCode: 200
  statusText: OK
  headers:
    Content-Type: application/json
  body:
    type: json
    content: |-
      {
        "task": [
          {
            "associatedEntities": [
              "broker"
            ],
            "taskInputMappings": {
              "application": "com.myspace.mortgage_app.Application",
              "TaskName": "String",
              "Skippable": "Object",
              "GroupId": "Object"
            },
            "taskOutputMappings": {
              "application": "com.myspace.mortgage_app.Application"
            },
            "task-id": "6",
            "task-name": "Correct Data",
            "task-priority": 0,
            "task-comment": "",
            "task-created-by": "",
            "task-skippable": false,
            "task-form-name": "CorrectData"
          },
          {
            "associatedEntities": [
              "approver"
            ],
            "taskInputMappings": {
              "application": "com.myspace.mortgage_app.Application",
              "TaskName": "String",
              "Skippable": "Object",
              "GroupId": "Object"
            },
            "taskOutputMappings": {
              "inlimit": "Boolean"
            },
            "task-id": "8",
            "task-name": "Qualify",
            "task-priority": 0,
            "task-comment": "",
            "task-created-by": "",
            "task-skippable": false,
            "task-form-name": "Qualify"
          },
          {
            "associatedEntities": [
              "manager"
            ],
            "taskInputMappings": {
              "inlimit": "Boolean",
              "application": "com.myspace.mortgage_app.Application",
              "TaskName": "String",
              "Skippable": "Object",
              "GroupId": "Object"
            },
            "taskOutputMappings": {},
            "task-id": "10",
            "task-name": "Final Approval",
            "task-priority": 0,
            "task-comment": "",
            "task-created-by": "",
            "task-skippable": false,
            "task-form-name": "FinalApproval"
          }
        ]
      }
order: 1000
