$kind: http-request
url: "{{baseUrl}}/server/queries/variables/processes/tasks?page=0&pageSize=10&o\
  rderBy=string&asc=true"
method: POST
headers:
  Content-Type: application/json
  Accept: application/json
queryParams:
  - key: page
    value: "0"
    description: optional pagination - at which page to start, defaults to 0 (meaning first)
  - key: pageSize
    value: "10"
    description: optional pagination - size of the result, defaults to 10
  - key: orderBy
    value: string
    description: optional sort column
  - key: asc
    value: "true"
    description: optional sort direction - true ascending, false descending
body:
  type: json
  content: string
examples: ./.resources/Queries process tasks by variables.resources/examples
order: 1000
