$kind: http-request
url: "{{baseUrl}}/server/queries/tasks/instances/process/:processInstanceId?sta\
  tus=Suspended&status=Exited&page=0&pageSize=10&sort=string&sortOrder=true"
method: GET
headers:
  Accept: application/json
queryParams:
  - key: status
    value: Suspended
    description: optional task status (Created, Ready, Reserved, InProgress,
      Suspended, Completed, Failed, Error, Exited, Obsolete)
  - key: status
    value: Exited
    description: optional task status (Created, Ready, Reserved, InProgress,
      Suspended, Completed, Failed, Error, Exited, Obsolete)
  - key: page
    value: "0"
    description: optional pagination - at which page to start, defaults to 0 (meaning first)
  - key: pageSize
    value: "10"
    description: optional pagination - size of the result, defaults to 10
  - key: sort
    value: string
    description: optional sort column, no default
  - key: sortOrder
    value: "true"
    description: optional sort direction (asc, desc) - defaults to asc
pathVariables:
  - key: processInstanceId
    value: "3284"
    description: process instance id to filter task instances
examples: ./.resources/Returns task instances associated with a specified
  process instance..resources/examples
order: 1000
