$kind: http-example
request:
  url: "{{baseUrl}}/server/admin/containers/:containerId/tasks/errors/:errorId"
  method: GET
  pathVariables:
    - key: containerId
      value: evaluation_1.0.0-SNAPSHOT
      description: container id that error belongs to
    - key: errorId
      value: xxx-yyy-zzz
      description: identifier of the execution error to load
response:
  statusCode: 500
  statusText: Internal Server Error
  body:
    type: text
    content: ""
order: 3000
