$kind: http-request
url: "{{baseUrl}}/server/containers/:containerId/cases/instances/:caseId/tasks"
method: POST
headers:
  Content-Type: application/json
pathVariables:
  - key: containerId
    value: evaluation_1.0.0-SNAPSHOT
    description: container id that case instance belongs to
  - key: caseId
    value: CASE-00000000001
    description: identifier of the case instance
body:
  type: json
  content: string
examples: ./.resources/Adds a dynamic user task or service task to the specified
  case instance..resources/examples
order: 2000
