$kind: http-request
url: "{{baseUrl}}/server/config"
method: POST
headers:
  Content-Type: application/json
  Accept: application/json
body:
  type: json
  content: ""
examples: ./.resources/Executes one or more KIE Server commands for
  server-related or container-related operations.resources/examples
order: 1000
