$kind: http-example
request:
  url: "{{baseUrl}}/server/containers/:containerId/cases/instances/:caseId/roles"
  method: GET
  headers:
    Accept: application/json
  pathVariables:
    - key: containerId
      value: evaluation_1.0.0-SNAPSHOT
      description: container id that case instance belongs to
    - key: caseId
      value: CASE-00000000001
      description: identifier of the case instance
response:
  statusCode: 200
  statusText: OK
  headers:
    Content-Type: application/json
  body:
    type: json
    content: |-
      {
        "role-assignments": [
          {
            "name": "owner",
            "users": [
              "baAdmin"
            ],
            "groups": []
          },
          {
            "name": "manager",
            "users": [
              "baAdmin"
            ],
            "groups": []
          },
          {
            "name": "supplier",
            "users": [],
            "groups": [
              "IT"
            ]
          }
        ]
      }
order: 1000
