$kind: http-request
url: "{{baseUrl}}/server/queries/cases/instances/:caseId/tasks/instances/stakeh\
  olders?user=string&status=Suspended&status=Exited&page=0&pageSize=10&sort=str\
  ing&sortOrder=true"
method: GET
headers:
  Accept: application/json
queryParams:
  - key: user
    value: string
    description: optional user id to be used instead of authenticated user - only
      when bypass authenticated user is enabled
  - key: status
    value: Suspended
    description: optional task status (Created, Ready, Reserved, InProgress,
      Suspended, Completed, Failed, Error, Exited, Obsolete)
  - key: status
    value: Exited
    description: optional task status (Created, Ready, Reserved, InProgress,
      Suspended, Completed, Failed, Error, Exited, Obsolete)
  - key: page
    value: "0"
    description: optional pagination - at which page to start, defaults to 0 (meaning first)
  - key: pageSize
    value: "10"
    description: optional pagination - size of the result, defaults to 10
  - key: sort
    value: string
    description: optional sort column, no default
  - key: sortOrder
    value: "true"
    description: optional sort direction (asc, desc) - defaults to asc
pathVariables:
  - key: caseId
    value: CASE-0000000001
    description: case instance identifier that tasks should belong to
examples: ./.resources/Returns tasks for stakeholders in a specified case
  instance..resources/examples
order: 1000
