$kind: http-request
url: "{{baseUrl}}/server/containers/:containerId/tasks/:taskInstanceId/contents\
  /:contentId"
method: DELETE
pathVariables:
  - key: containerId
    value: evaluation_1.0.0-SNAPSHOT
    description: container id that task instance belongs to
  - key: taskInstanceId
    value: "123"
    description: identifier of the task instance that content belongs to
  - key: contentId
    value: "567"
    description: identifier of the content to be deleted
examples: ./.resources/Deletes output data by content ID from a specified task
  instance..resources/examples
order: 1000
