$kind: http-example
request:
  url: "{{baseUrl}}/server/admin/containers/:containerId/tasks/:taskInstanceId/po\
    t-owners?user=string&remove=false"
  method: PUT
  headers:
    Content-Type: application/json
  queryParams:
    - key: user
      value: string
      description: optional user id to be used instead of authenticated user - only
        when bypass authenticated user is enabled
    - key: remove
      value: "false"
      description: optional flag that indicates if existing potential owners should be
        removed, defaults to false
  pathVariables:
    - key: containerId
      value: evaluation_1.0.0-SNAPSHOT
      description: container id that task instance belongs to
    - key: taskInstanceId
      value: "123"
      description: identifier of task instance to be updated
  body:
    type: json
    content: string
response:
  statusCode: 404
  statusText: Not Found
  body:
    type: text
    content: ""
order: 1000
