$kind: http-example
request:
  url: "{{baseUrl}}/server/queries/tasks/instances/:taskInstanceId?withSLA=false"
  method: GET
  queryParams:
    - key: withSLA
      value: "false"
      description: optional include SLA data - defaults to false
  pathVariables:
    - key: taskInstanceId
      value: "3284"
      description: task id to load task instance
response:
  statusCode: 404
  statusText: Not Found
  body:
    type: text
    content: ""
order: 2000
