$kind: http-example
request:
  url: "{{baseUrl}}/server/containers/:containerId/tasks/:taskInstanceId/comments"
  method: GET
  headers:
    Accept: application/json
  pathVariables:
    - key: containerId
      value: evaluation_1.0.0-SNAPSHOT
      description: container id that task instance belongs to
    - key: taskInstanceId
      value: "123"
      description: identifier of the task instance that comments should be loaded for
response:
  statusCode: 200
  statusText: OK
  headers:
    Content-Type: application/json
  body:
    type: json
    content: >-
      {
        "task-comment": [
          {
            "comment-id": 1,
            "comment": "Ensure that this self evaluation is completed before the HR and PM evaluations.",
            "comment-added-by": "baAdmin",
            "comment-added-at": {
              "java.util.Date": 1540238822132
            }
          },
          {
            "comment-id": 2,
            "comment": "Task must be assigned to administrator.",
            "comment-added-by": "baAdmin",
            "comment-added-at": {
              "java.util.Date": 1540238822140
            }
          }
        ]
      }
order: 1000
