$kind: http-request
url: "{{baseUrl}}/server/containers/:containerId/forms/tasks/:taskInstanceId?la\
  ng=en&filter=true&type=ANY&marshallContent=true&user=string"
method: GET
headers:
  Accept: application/xml
queryParams:
  - key: lang
    value: en
    description: optional language that the form should be found for
  - key: filter
    value: "true"
    description: optional filter flag if form should be filtered or returned as is
  - key: type
    value: ANY
    description: optional type of the form, defaults to ANY so system will find the
      most current one
  - key: marshallContent
    value: "true"
    description: optional marshall content flag if the content should be transformed
      or not, defaults to true
  - key: user
    value: string
    description: optional user id to be used instead of authenticated user - only
      when bypass authenticated user is enabled
pathVariables:
  - key: containerId
    value: evaluation_1.0.0-SNAPSHOT
    description: container id that task instance belongs to
  - key: taskInstanceId
    value: "123"
    description: identifier of task instance that form should be fetched for
examples: ./.resources/Returns the form information for a specified task
  instance..resources/examples
order: 2000
