$kind: http-request
url: "{{baseUrl}}/server/containers/:containerId/tasks/:taskInstanceId/priority"
method: PUT
headers:
  Content-Type: application/json
pathVariables:
  - key: containerId
    value: evaluation_1.0.0-SNAPSHOT
    description: container id that task instance belongs to
  - key: taskInstanceId
    value: "123"
    description: identifier of the task instance where priority should be updated
body:
  type: json
  content: string
examples: ./.resources/Updates the priority of a specified task
  instance..resources/examples
order: 1000
