$kind: http-request
url: "{{baseUrl}}/server/containers/:containerId/tasks/:taskInstanceId/attachme\
  nts?user=string&name=string"
method: POST
headers:
  Content-Type: application/json
  Accept: application/json
queryParams:
  - key: user
    value: string
    description: optional user id to be used instead of authenticated user - only
      when bypass authenticated user is enabled
  - key: name
    value: string
    description: name of the attachment to be added
pathVariables:
  - key: containerId
    value: evaluation_1.0.0-SNAPSHOT
    description: container id that task instance belongs to
  - key: taskInstanceId
    value: "123"
    description: identifier of the task instance that attachment should be added to
body:
  type: json
  content: string
examples: ./.resources/Adds an attachment to a specified task instance and
  returns the ID of the new attachment..resources/examples
order: 3000
