$kind: http-example
request:
  url: "{{baseUrl}}/server/queries/tasks/instances/workitem/:workItemId"
  method: GET
  pathVariables:
    - key: workItemId
      value: "3284"
      description: work item id to load task associated with
response:
  statusCode: 500
  statusText: Internal Server Error
  body:
    type: text
    content: ""
order: 3000
