$kind: http-example
request:
  url: "{{baseUrl}}/server/queries/cases/variables/cases/tasks?page=0&pageSize=10"
  method: POST
  headers:
    Content-Type: application/json
    Accept: application/json
  queryParams:
    - key: page
      value: "0"
      description: optional pagination - at which page to start, defaults to 0
        (meaning first)
    - key: pageSize
      value: "10"
      description: optional pagination - size of the result, defaults to 10
  body:
    type: json
    content: string
response:
  statusCode: 200
  statusText: OK
  headers:
    Content-Type: application/json
  body:
    type: json
    content: |-
      {
        "case-user-task-with-vars-instance": [
          {
            "id": 3938,
            "name": "string",
            "description": "string",
            "actual-owner": "string",
            "correlation-key": "string",
            "potential-owners": [
              "string",
              "string"
            ],
            "case-definition-id": "string",
            "process-instance-id": 3532,
            "case-id": "string",
            "task-instance-input-variables": {
              "key_0": {},
              "key_1": {},
              "key_2": {}
            },
            "process-instance-variables": {
              "key_0": {}
            },
            "case-instance-variables": {
              "key_0": {}
            },
            "status": "string"
          },
          {
            "id": 9989,
            "name": "string",
            "description": "string",
            "actual-owner": "string",
            "correlation-key": "string",
            "potential-owners": [
              "string",
              "string"
            ],
            "case-definition-id": "string",
            "process-instance-id": 4358,
            "case-id": "string",
            "task-instance-input-variables": {
              "key_0": {},
              "key_1": {}
            },
            "process-instance-variables": {
              "key_0": {},
              "key_1": {},
              "key_2": {}
            },
            "case-instance-variables": {
              "key_0": {}
            },
            "status": "string"
          }
        ]
      }
order: 1000
