$kind: http-example
request:
  url: "{{baseUrl}}/server/containers/:containerId/tasks/:taskInstanceId?withInpu\
    tData=true&withOutputData=true&withAssignments=true"
  method: GET
  headers:
    Accept: application/json
  queryParams:
    - key: withInputData
      value: "true"
      description: optionally loads task input data
    - key: withOutputData
      value: "true"
      description: optionally loads task output data
    - key: withAssignments
      value: "true"
      description: optionally loads task people assignments
  pathVariables:
    - key: containerId
      value: evaluation_1.0.0-SNAPSHOT
      description: container id that task instance belongs to
    - key: taskInstanceId
      value: "123"
      description: identifier of the task instance that should be loaded
response:
  statusCode: 200
  statusText: OK
  headers:
    Content-Type: application/json
  body:
    type: json
    content: |-
      {
        "task-id": 1,
        "task-priority": 0,
        "task-name": "Self Evaluation",
        "task-subject": null,
        "task-description": "Please perform a self-evalutation.",
        "task-type": null,
        "task-form": null,
        "task-status": "Ready",
        "task-actual-owner": "kiesu",
        "task-created-by": "Jane",
        "task-created-on": {
          "java.util.Date": 1539623679113
        },
        "task-activation-time": {
          "java.util.Date": 1539623679113
        },
        "task-expiration-time": null,
        "task-skippable": null,
        "task-workitem-id": null,
        "task-process-instance-id": 4,
        "task-parent-id": null,
        "task-process-id": "Mortgage_Process.MortgageApprovalProcess",
        "task-container-id": "mortgage-process_1.0.0-SNAPSHOT",
        "task-pot-owners": "Jane",
        "task-excl-owners": null,
        "task-business-admins": "John",
        "task-input-data": null,
        "task-output-data": null
      }
order: 1000
