$kind: http-example
request:
  url: "{{baseUrl}}/server/containers/:containerId/tasks/:taskInstanceId?withInpu\
    tData=true&withOutputData=true&withAssignments=true"
  method: GET
  queryParams:
    - key: withInputData
      value: "true"
      description: optionally loads task input data
    - key: withOutputData
      value: "true"
      description: optionally loads task output data
    - key: withAssignments
      value: "true"
      description: optionally loads task people assignments
  pathVariables:
    - key: containerId
      value: evaluation_1.0.0-SNAPSHOT
      description: container id that task instance belongs to
    - key: taskInstanceId
      value: "123"
      description: identifier of the task instance that should be loaded
response:
  statusCode: 500
  statusText: Internal Server Error
  body:
    type: text
    content: ""
order: 3000
